[SC-248] Exclude synapse userProfile data
Sage-Bionetworks-IT/cfn-cr-synapse-tagger pull request #18
Opened 2020-10-02 14:46 UTC by zaro0508

S3 buckets do not allow tag values with certain characters, like a
comma (i.e. Seattle, WA).  This change excludes additional userProfile data[1]
that may contain restricted characters.

The only doc i've run across that touches on character restrictions for tag
values is in the EC2 docs[2]

"Although EC2 allows for any character in its tags, other services are more
restrictive. The allowed characters across services are: letters, numbers,
and spaces representable in UTF-8, and the following characters: + - = . _ : / @."

So it looks like it's not consistent across services. Commas are allowed for
EC2s tags but not for S3 tags.

[1] http://rest-docs.synapse.org/rest/org/sagebionetworks/repo/model/UserProfile.html
[2] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions

2020-10-02 16:11 UTC, brucehoff requested changes
For this to definitively prevent disallowed characters from causing errors, we would have to add:
firstName, lastName, company, teamName and (maybe url).  I would suggest either (1) replacing this 'excludes' list with an 'includes' list that just includes fields that can't have disallowed characters (just ownerId and userName, I think...), or (2) allow the currently included field but sanitize them to remove any disallowed characters (or replace the disallowed characters with something like a space or underscore).

The problem with the proposed change (aside from missing the fields listed above) is that if the user profile added another field, and a user populated that field using characters disallowed in tag values by AWS, then the error would recur.

2020-10-02 16:42 UTC, tthyer requested changes
I concur with Bruce

2020-10-02 17:07 UTC, tthyer approved these changes

2020-10-02 19:32 UTC, brucehoff requested changes
"ownerId" - a number, represented as a string (from a MySQL sequence)
"userName" - restricted to letters, numbers, ".", "-", "_"
"firstName", "lastName", "company" - can be anything, even non-ASCII characters, so they would have to be sanitized to ensure AWS doesn't reject them as tag values

2020-10-02 19:46 UTC, zaro0508 commented
> "firstName", "lastName", "company" - can be anything, even non-ASCII characters, so they would have to be sanitized to ensure AWS doesn't reject them as tag values

The documentation isn't specific about which chars are not acceptable. What characters would you suggest we reject?  Maybe you could help with a regex?

2020-10-06 21:25 UTC, brucehoff approved these changes
Looks great!

2020-10-06 21:38 UTC, merged