Skip applying tags if ENV VAR is not defined.
Sage-Bionetworks-IT/cfn-cr-synapse-tagger pull request #23
Opened 2020-11-10 20:29 UTC by zaro0508

We had to revert PR https://github.com/Sage-Bionetworks/scipool-infra/pull/225
because this lambda would fail to run if dependent ENV VARS are not setup.
For example the `MarketplaceProductCodeSC` has not been setup in production
environments because we have not completed development and testing of
the aws marketplace integration in the develop environment yet.

This change makes it so that the labmda doesn't error when the ENV VARs
are not setup.  Instead the lambda will just skip applying tags if the
required ENV VAR is not defined.  This will allow us to deploy the
lambda in all environments.

2020-11-11 21:07 UTC, brucehoff requested changes
Looks good, just one small typo to change.

2020-11-11 23:22 UTC, zaro0508 commented on set_tags/utils.py
> +    log.warning(f'cannot get envirooment variable: {env_var}')
fixed

2020-11-12 01:08 UTC, brucehoff approved these changes

2020-11-12 17:29 UTC, brucehoff approved these changes
Sorry, I thought I had approved this yesterday.

2020-11-12 17:38 UTC, tthyer approved these changes
LGTM qualified -- like the idea of decoupling but don't fully know the effects of these tags being missing

2020-11-12 18:21 UTC, merged